# SwiftLint Configuration for MiniCity
# Enforces consistent code style and best practices

disabled_rules:
  - trailing_whitespace # Conflicts with Xcode auto-formatting
  - todo # We want to keep TODOs
  - line_length # Metal shader code can have long lines

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

excluded:
  - Carthage
  - Pods
  - DerivedData
  - .build
  - build
  - ${DERIVED_DATA}

analyzer_rules:
  - unused_declaration
  - unused_import

file_length:
  warning: 600
  error: 1200

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - ID
    - URL
    - UI

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - x
    - y
    - z
    - w
    - r
    - g
    - b
    - a
    - i
    - j
    - k
    - id
    - dx
    - dy
    - dz

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

cyclomatic_complexity:
  warning: 15
  error: 20

custom_rules:
  no_print_statements:
    name: "Print Statements"
    regex: '\bprint\s*\('
    message: "Use proper logging instead of print statements"
    severity: warning
    
  force_unwrapping:
    name: "Force Unwrapping"
    regex: '(?<!\\)!(?!\.self)'
    message: "Avoid force unwrapping, use guard or if let"
    severity: warning
    
  mark_format:
    name: "MARK Format"
    regex: '// MARK: [^-]'
    message: "MARK comments should include a hyphen (// MARK: - Section)"
    severity: warning

reporter: "emoji" # or xcode, json, csv, checkstyle, html